using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using TaxReturns.Plugins.Abstractions.Application.Models;
using TaxReturns.Plugins.Abstractions.Application.Models.Enums;
using TaxReturns.Plugins.Abstractions.Application.Models.Inputs;
using TaxReturns.Plugins.Abstractions.Application.Models.Outputs;

namespace TaxReturns.Plugins.Abstractions.Application.Plugins
{
    public interface ITaxPlugin:ITaxCapability
    {
        #region "Request/Result Metadata"

        /// <summary>
        /// The type of the request object that is used to submit a return for the Tax Type that this plugin supports.
        /// </summary>
        Type TaxReturnRequestType { get; }
        /// <summary>
        /// The type of the result object that is returned after submitting a return for the Tax Type that this plugin supports.
        /// </summary>
        Type TaxReturnType { get; }


        /// <summary>
        /// The type of the request object that is used to calculate taxes for the Tax Type that this plugin supports.
        /// </summary>
        Type CalculationRequestType { get; }
        /// <summary>
        /// The type of the result object that is returned after calculating taxes for the Tax Type that this plugin supports.
        /// </summary>
        Type TaxAssessmentType { get; }


        /// <summary>
        /// The type of the request object that is used to save a draft return for the Tax Type that this plugin supports.
        /// </summary>
        Type DraftRequestType { get; }
        /// <summary>
        /// The type of the result object that is returned after saving a draft return for the Tax Type that this plugin supports.
        /// </summary>
        Type DraftReturnType { get; }
        #endregion

        #region "Plugin Infrastructure"
        /// <summary>
        /// Register plugin-specific DbContexts, services, and repositories into DI.
        /// </summary>
        void RegisterServices(IServiceCollection services, string connectionString);

        #endregion

        #region "Core lifecycle"

        /// <summary>
        /// Initialises a Blank Return. This function retrieves that Taxpayer record and the TaxPeriods that are available for filing
        /// </summary>
        /// <param name="TIN">The Taxpayer Identification Number (TIN)</param>
        /// <returns>The Return Context which contains the details of the Taxpayer and the Taxperiods that are available (open) for filing for that particular Taxpayer</returns>
        Task<OperationResult<ReturnContext>> InitializeReturn(string TIN);

        /// <summary>
        /// Calculates Taxes based on the request data that has been submitted.
        /// During this process, the return data submitted is also validated to ensure that all mandatory fields have been input
        /// NOTE: This only calculates the Taxes for display to the Taxpayer
        /// </summary>
        /// <param name="calculationRequest"></param>
        /// <returns>The Tax Assessment that has details of the calculated taxes to be paid by the Taxpayer</returns>
        Task<OperationResult<object>> CalculateTax(object calculationRequest);

        /// <summary>
        /// Submits a return for processing and also posts a ledger entry for the return
        /// During submission, the return is validated and the system also assesses if there is need to charge late filing penalties.
        /// </summary>
        /// <param name="taxReturnRequest">The return data to be saved as draft</param>
        /// <returns>The submitted Tax Return with the ReturnId and any penalties that could have been charged because of late filing if applicable</returns>
        Task<OperationResult<object>> ProcessReturn(object taxReturnRequest); //tax return to have submission date | Also returns late filing penalties

        /// <summary>
        /// Saves a draft of the Return that has been input by the Taxpayer
        /// </summary>
        /// <param name="draftRequest">The return data to be saved as draft</param>
        /// <returns>The draft return with a DraftId generated by the system.</returns>
        Task<OperationResult<object>> SaveDraft(object draftRequest);

        #endregion

        #region "Payment Handling"

        /// <summary>
        /// Submits a request to ePayments for generation of PRNs.
        /// The Taxpayer is supposed to have selected returns and/or penalties whose PRN is supposed to be generated for.
        /// The PRN will be generated for all selected items.
        /// </summary>
        /// <param name="returns">The returns whose amounts are supposed to be a part of the PRN</param>
        /// <param name="penalties">The penalties whose amounts are supposed to be a part of the PRN</param>
        /// <returns></returns>
        Task<OperationResult<PRNReceipt>> GeneratePRN(List<string> returnIds, List<string> penaltyIds);

        /// <summary>
        /// Processes a payment and updates the returns and/or penalties that were attached to the specified PRN
        /// </summary>
        /// <param name="notification">Payment Notification details, for instance, PRN etc...</param>
        /// <returns>Payment Confirmation</returns>
        Task<OperationResult<PaymentConfirmation>> ProcessPayment(PaymentNotification notification);

        #endregion

        #region "Return Queries"

        /// <summary>
        /// Gets the details of a Return from the System
        /// </summary>
        /// <param name="returnId">The system generated Id assigned to the Return</param>
        /// <param name="TIN">The Taxpayer Identification Number (TIN). This is important to ensure that Taxpayers only have access to their returns. The system SHOULD validate TIN specified is attached to the Return Id</param>
        /// <returns>The Return</returns>
        Task<OperationResult<object>> GetReturn(string returnId, string TIN);

        /// <summary>
        /// Gets the details of a Draft Return from the System
        /// </summary>
        /// <param name="draftId">The system generated Id assigned to the Draft Return</param>
        /// <param name="TIN">The Taxpayer Identification number (TIN). This is important to ensure that Taxpayers only have access to their returns. The system SHOULD validate TIN specified is attached to the Return Id</param>
        /// <returns></returns>
        Task<OperationResult<object>> GetDraftReturn(string draftId, string TIN);

        /// <summary>
        /// Lists returns for the specified TIN using the specified filter
        /// </summary>
        /// <param name="TIN">The Taxpayer Identification Number (TIN)</param>
        /// <param name="statusfilter">The return status, e.g. Submitted, Pending Payment, Paid or blank. If no filter is specified the system returns all returns</param>
        /// <returns>List of Returns</returns>
        Task<OperationResult<List<object>>> ListReturns(string TIN, ReturnStatus? statusfilter = null);


        #endregion

        #region "Penalty Queries"
        /// <summary>
        /// Gets the details of a penalty from the system
        /// </summary>
        /// <param name="penaltyId">The system generated Id given to the Penalty</param>
        /// <param name="TIN">The Taxpayer Identification Number (TIN)</param>
        /// <returns>The Penalty record</returns>
        Task<OperationResult<Penalty>> GetPenalty(string penaltyId, string TIN);

        /// <summary>
        /// Lists penalties charged to the Taxpayer using the specified filters
        /// </summary>
        /// <param name="TIN">The Taxpayer Identification Number (TIN)</param>
        /// <param name="typeFilter">The penalty type, e.g. Late Filing or Late Payment</param>
        /// <param name="statusfilter">The penalty status, e.g. Paid or PendingPayment</param>
        /// <returns>The list of penalties</returns>
        Task<OperationResult<List<Penalty>>> ListPenalties(string TIN, PenaltyType? typeFilter = null, PenaltyStatus? statusfilter = null);
        #endregion

        #region "Tax Periods and Filing History"
        
        /// <summary>
        /// Gets a list of Open Tax Periods, i.e. periods that are open for filing, for the specified Taxpayer
        /// </summary>
        /// <param name="TIN">The Taxpayer Identification Number (TIN)</param>
        /// <returns>List of Tax Periods</returns>
        Task<OperationResult<List<TaxPeriod>>> GetOpenTaxPeriods(string TIN);

        /// <summary>
        /// Gets the Filing History for the Taxpayer given a Tax Year. The system gets all the Tax Periods for the Year and shows whether a return was filed and was paid for that period
        /// </summary>
        /// <param name="TIN">The Taxpayer Identification Number</param>
        /// <param name="TaxYear">The Tax Year</param>
        /// <returns></returns>
        Task<OperationResult<List<FilingRecord>>> GetFilingHistory(string TIN, string TaxYear);
        #endregion
    }
}
